name: tag_styled_text
description: Straightforward xml tag based (rich) styling on Text widgets
version: 0.1.0
homepage: https://github.com/williamhjcho/xml_styled_text
repository: https://github.com/williamhjcho/xml_styled_text
issue_tracker: https://github.com/williamhjcho/xml_styled_text/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  meta: ^1.17.0
  mocktail: ^1.0.4
